/** Rank options: value is Hebrew (stored in DB / sent to API). */
export const RANK_OPTIONS: { value: string; labelHe: string; labelEn: string }[] = [
  { value: 'טוראי (טור׳)', labelHe: 'טוראי (טור׳)', labelEn: 'Private' },
  { value: 'טוראי ראשון (טר״ש)', labelHe: 'טוראי ראשון (טר״ש)', labelEn: 'Lance Corporal' },
  { value: 'רב טוראי (רב״ט)', labelHe: 'רב טוראי (רב״ט)', labelEn: 'Corporal' },
  { value: 'סמל (סמ״ל)', labelHe: 'סמל (סמ״ל)', labelEn: 'Sergeant' },
  { value: 'סמל ראשון (סמ״ר)', labelHe: 'סמל ראשון (סמ״ר)', labelEn: 'First Sergeant' },
  { value: 'רב סמל (רס״ל)', labelHe: 'רב סמל (רס״ל)', labelEn: 'Master Sergeant' },
  { value: 'רב סמל ראשון (רס״ר)', labelHe: 'רב סמל ראשון (רס״ר)', labelEn: 'Sergeant First Class' },
  { value: 'רב סמל מתקדם (רס״מ)', labelHe: 'רב סמל מתקדם (רס״מ)', labelEn: 'Advanced Sergeant Major' },
  { value: 'רב סמל בכיר (רס״ב)', labelHe: 'רב סמל בכיר (רס״ב)', labelEn: 'Senior Sergeant Major' },
  { value: 'רב סמל ראשון בכיר (רס״ב״ר)', labelHe: 'רב סמל ראשון בכיר (רס״ב״ר)', labelEn: 'Senior First Sergeant' },
  { value: 'סגן משנה (סג״מ)', labelHe: 'סגן משנה (סג״מ)', labelEn: 'Second Lieutenant' },
  { value: 'סגן (סג״ן)', labelHe: 'סגן (סג״ן)', labelEn: 'Lieutenant' },
  { value: 'סרן (סרן)', labelHe: 'סרן (סרן)', labelEn: 'Captain' },
  { value: 'רב סרן (רס״ן)', labelHe: 'רב סרן (רס״ן)', labelEn: 'Major' },
  { value: 'סגן אלוף (סא״ל)', labelHe: 'סגן אלוף (סא״ל)', labelEn: 'Lieutenant Colonel' },
  { value: 'אלוף משנה (אל״ם)', labelHe: 'אלוף משנה (אל״ם)', labelEn: 'Colonel' },
  { value: 'תת אלוף (תא״ל)', labelHe: 'תת אלוף (תא״ל)', labelEn: 'Brigadier General' },
  { value: 'אלוף (אלוף)', labelHe: 'אלוף (אלוף)', labelEn: 'Major General' },
  { value: 'רב אלוף (רא״ל)', labelHe: 'רב אלוף (רא״ל)', labelEn: 'Lieutenant General' },
  { value: 'קצין מקצועי אקדמאי (קמ״א)', labelHe: 'קצין מקצועי אקדמאי (קמ״א)', labelEn: 'Academic Professional Officer' },
  { value: 'קצין אקדמאי בכיר (קא״ב)', labelHe: 'קצין אקדמאי בכיר (קא״ב)', labelEn: 'Senior Academic Officer' },
  { value: 'קצין מקצועי שיניים (קמ״ש)', labelHe: 'קצין מקצועי שיניים (קמ״ש)', labelEn: 'Dental Professional Officer' },
  { value: 'רבץ (רב״ץ)', labelHe: 'רבץ (רב״ץ)', labelEn: 'Quartermaster' },
  { value: 'קרפ (קר״פ)', labelHe: 'קרפ (קר״פ)', labelEn: 'Corps Quartermaster' },
  { value: 'קצין אקדמאי מיוחד (קא״ם)', labelHe: 'קצין אקדמאי מיוחד (קא״ם)', labelEn: 'Special Academic Officer' },
]
